### ISSUE TITLE
Docker Window Image not utilizing the ARGS correctly

### ISSUE THREAD

**Issue by brucemanson** [Microsoft/aspnet-docker#60]
HOST OS: Windows 10

Client:
 Version:       17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:              Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true 

**Dockerfile:** 
FROM microsoft/aspnet
ARG buildarea=production
RUN echo %buildarea%

**Docker RUN**
docker image build -t company/test --build-arg buildarea=staging .

The RUN echo simply re-echo's the %buildarea% and not the expected word "staging"

If I change the base image to microsoft/iis or microsoft/windowsservercore or microsoft/nanoserver 
the --build-arg works correctly if supplied else it defaults to "production" as expected.

The failures I have picked up so far appear to be in: 
- microsoft/aspnet
- microsoft/aspnet:4.6.2

**Comment by MichaelSimons** [comment]
@brucemanson - The reason for this is because the `microsoft/aspnet` image has specified `PowerShell` as the `SHELL` - see https://github.com/Microsoft/aspnet-docker/blob/master/4.7.1-windowsservercore-ltsc2016/runtime/Dockerfile#L3.  Because of this, you must use the PowerShell constructs to reference environment variables.

```
FROM microsoft/aspnet
ARG buildarea=production
RUN echo $env:buildarea
```
