### ISSUE TITLE
ASP.NET Windows container with support for web.config overrides at startup

### ISSUE THREAD

**Issue by natemcmaster** [microsoft/aspnet-docker#70]
_From @spboyer on November 20, 2017 20:0_

See https://github.com/anthonychu/aspnet-env-docker

Add image variation to have web.config settings pulled from ENV.

cc: @anthonychu, @richlander 

_Copied from original issue: aspnet/aspnet-docker#333_

**Comment by anthonychu** [comment]
The motivation behind this is to create a good story for folks who can't or don't want to update to 4.7.1 and make code changes in order to use environment variables for configuration, like typical Docker images.

The image I created is just a proof of concept, but it shows that it's possible to support a true lift-and-shift scenario where we can simply copy the build output into the image with zero changes. At startup, we're able to configure the container using a web.config transform file and/or environment variables.

I don't think a separate image needs to be created to support this. If done properly, these capabilities can be added to the existing image with no impact on perf or image size. And it would be 100% backward compatible with the existing microsoft/aspnet images today.

**Comment by spboyer** [comment]
I agree with @anthonychu thoughts on this. @taylorb-microsoft thoughts here?

**Comment by taylorb-microsoft** [comment]
We've definitely had requests for this type of functionality.  What's the argument against it?

**Comment by richlander** [comment]
Isn't this something best handled via multi-stage build instead of container startup?

**Comment by anthonychu** [comment]
We would like to follow the common pattern of building an image once, then deploying that image to different environments. To do this, the container needs to be configurable for each environment at startup.

**Comment by taylorb-microsoft** [comment]
I agree with both Richard and Anthony :)...  There are many settings that I think would be best configured during image build but I also see value in run-time configuration and this is something we've heard from customers as well... Today if I wanted to temporarily change a setting (like error pages for example) I have to either build a new container image or interactively modify the container - I can see a much better pattern being starting up an additional container (outside of a load balancer maybe) with that value changed...

Especially as we push more and more into ci/cd - run/start time configuration seems like it will become more valuable.

**Comment by csharpfritz** [comment]
.NET 4.7.1 is an in-place update for and no code changes are needed to load data into web.config or app.config using ConfigurationBuilders.  Add the NuGet package, entries in your config file for what you would like to update, and it works.  No recompile is needed, just change the target framework in your web.config file.
The challenge with adding a script to the Docker container start process is that the configuration of NetFx applications is very complex and we wanted a robust solution that addresses all of these issues and could target any node in the Configuration.
